// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Omkhar Arasaratnam

// Code generated by workcell-hostutil adapters gen from adapters/*/adapter.toml. DO NOT EDIT.

package providerid

// AllProviders is the canonical iteration order for Workcell adapters:
// every manifest whose tier is not planned. Many call sites (validators,
// manifests, sort orders) depend on a stable order; use this slice
// instead of declaring a local one.
var AllProviders = []string{"claude", "codex", "copilot", "gemini"}

// CredentialMetadataProviders is the canonical order for provider credential
// metadata tables: every manifest that declares credentials. Membership here
// is not a support-tier claim.
var CredentialMetadataProviders = []string{"claude", "codex", "copilot", "gemini"}
