# shellcheck shell=bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Omkhar Arasaratnam

# Code generated by workcell-hostutil adapters gen from adapters/*/adapter.toml. DO NOT EDIT.

# workcell_supported_agent succeeds when $1 is a supported adapter id.
workcell_supported_agent() {
  case "$1" in
    claude | codex | copilot | gemini) ;;
    *)
      return 1
      ;;
  esac
}

# provider_endpoints prints the fixed egress endpoints of adapter $1.
provider_endpoints() {
  case "$1" in
    claude)
      echo "api.anthropic.com:443 claude.ai:443 console.anthropic.com:443"
      ;;
    codex)
      echo "api.openai.com:443 auth.openai.com:443 chatgpt.com:443"
      ;;
    copilot)
      echo "api.githubcopilot.com:443 api.individual.githubcopilot.com:443 api.github.com:443 github.com:443"
      ;;
    gemini)
      echo "generativelanguage.googleapis.com:443 ai.google.dev:443"
      ;;
    *)
      return 1
      ;;
  esac
}

# workcell_adapter_credential_keys prints the adapter-scoped credential keys.
workcell_adapter_credential_keys() {
  printf '%s\n' 'claude_api_key,claude_auth,claude_mcp,codex_auth,copilot_github_token,gemini_env,gemini_oauth,gemini_projects,gcloud_adc'
}
