// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Omkhar Arasaratnam

package adapters

import (
	"fmt"
	"go/format"
	"strings"
)

const generatedHeader = "// SPDX-License-Identifier: Apache-2.0\n// Copyright 2026 Omkhar Arasaratnam\n\n// Code generated by workcell-hostutil adapters gen from adapters/*/adapter.toml. DO NOT EDIT.\n\n"

// GenTargets maps each `workcell-hostutil adapters gen` target to its renderer.
var GenTargets = map[string]func([]Manifest) ([]byte, error){
	"data":           RenderDataGo,
	"providerid":     RenderProviderIDGo,
	"launcher-shell": RenderLauncherShell,
	"runtime-shell":  RenderRuntimeShell,
}

// RenderDataGo renders internal/adapters/data_gen.go: the providers registry
// row of every non-planned manifest, in manifest (name) order.
func RenderDataGo(manifests []Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(generatedHeader + "package adapters\n\n")
	b.WriteString("// providers is the canonical per-adapter registry, ordered to match\n")
	b.WriteString("// providerid stable ordering. Order is load-bearing for deterministic\n")
	b.WriteString("// rendering in the injection bundle (see ReservedTargets()).\n")
	b.WriteString("var providers = []providerDefinition{\n")
	for _, m := range manifests {
		if m.Tier == "planned" {
			continue
		}
		fmt.Fprintf(&b, "{\nid: %q,\nsharedCredentialsEnabled: %t,\ntables: providerTables{\n", m.ID, m.SharedCredentials)
		keys := make([]string, 0, len(m.Credentials))
		for _, c := range m.Credentials {
			keys = append(keys, c.Key)
		}
		writeStringSlice(&b, "credentialKeys", keys)
		b.WriteString("credentialContainerPaths: map[string]string{\n")
		for _, c := range m.Credentials {
			fmt.Fprintf(&b, "%q: %q,\n", c.Key, c.ContainerPath)
		}
		b.WriteString("},\n")
		writeStringSlice(&b, "reservedTargets", m.ReservedTargets)
		b.WriteString("},\n},\n")
	}
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}

// RenderProviderIDGo renders internal/providerid/providerid_gen.go: the
// provider id lists that follow from the manifests. DocumentKeys keeps its
// hand-written rendering order in providerid.go.
func RenderProviderIDGo(manifests []Manifest) ([]byte, error) {
	var supported, withCredentials []string
	for _, m := range manifests {
		if m.Tier != "planned" {
			supported = append(supported, m.ID)
		}
		if len(m.Credentials) > 0 {
			withCredentials = append(withCredentials, m.ID)
		}
	}
	var b strings.Builder
	b.WriteString(generatedHeader + "package providerid\n\n")
	b.WriteString("// AllProviders is the canonical iteration order for Workcell adapters:\n")
	b.WriteString("// every manifest whose tier is not planned. Many call sites (validators,\n")
	b.WriteString("// manifests, sort orders) depend on a stable order; use this slice\n")
	b.WriteString("// instead of declaring a local one.\n")
	fmt.Fprintf(&b, "var AllProviders = %s\n\n", goStringSlice(supported))
	b.WriteString("// CredentialMetadataProviders is the canonical order for provider credential\n")
	b.WriteString("// metadata tables: every manifest that declares credentials. Membership here\n")
	b.WriteString("// is not a support-tier claim.\n")
	fmt.Fprintf(&b, "var CredentialMetadataProviders = %s\n", goStringSlice(withCredentials))
	return format.Source([]byte(b.String()))
}

const shellHeader = "# shellcheck shell=bash\n# SPDX-License-Identifier: Apache-2.0\n# Copyright 2026 Omkhar Arasaratnam\n\n# Code generated by workcell-hostutil adapters gen from adapters/*/adapter.toml. DO NOT EDIT.\n"

// RenderLauncherShell renders scripts/lib/launcher/generated-adapters.sh: the
// supported --agent ids, the provider egress endpoints, and the adapter
// credential keys that scripts/workcell reads.
func RenderLauncherShell(manifests []Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(shellHeader)
	writeShellSupportedAgent(&b, manifests)
	b.WriteString("\n# provider_endpoints prints the fixed egress endpoints of adapter $1.\nprovider_endpoints() {\n  case \"$1\" in\n")
	var keys []string
	for _, m := range manifests {
		if m.Tier == "planned" {
			continue
		}
		fmt.Fprintf(&b, "    %s)\n      echo \"%s\"\n      ;;\n", m.ID, strings.Join(m.EgressEndpoints, " "))
		for _, c := range m.Credentials {
			keys = append(keys, c.Key)
		}
	}
	b.WriteString("    *)\n      return 1\n      ;;\n  esac\n}\n")
	fmt.Fprintf(&b, "\n# workcell_adapter_credential_keys prints the adapter-scoped credential keys.\nworkcell_adapter_credential_keys() {\n  printf '%%s\\n' '%s'\n}\n", strings.Join(keys, ","))
	return []byte(b.String()), nil
}

// RenderRuntimeShell renders runtime/container/generated-adapters.sh: the
// supported provider ids that the runtime wrappers read.
func RenderRuntimeShell(manifests []Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(shellHeader)
	writeShellSupportedAgent(&b, manifests)
	return []byte(b.String()), nil
}

func writeShellSupportedAgent(b *strings.Builder, manifests []Manifest) {
	var ids []string
	for _, m := range manifests {
		if m.Tier != "planned" {
			ids = append(ids, m.ID)
		}
	}
	b.WriteString("\n# workcell_supported_agent succeeds when $1 is a supported adapter id.\nworkcell_supported_agent() {\n  case \"$1\" in\n")
	fmt.Fprintf(b, "    %s) ;;\n    *)\n      return 1\n      ;;\n  esac\n}\n", strings.Join(ids, " | "))
}

func writeStringSlice(b *strings.Builder, field string, values []string) {
	fmt.Fprintf(b, "%s: []string{\n", field)
	for _, v := range values {
		fmt.Fprintf(b, "%q,\n", v)
	}
	b.WriteString("},\n")
}

func goStringSlice(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
