# shellcheck shell=bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Omkhar Arasaratnam

# Code generated by workcell-hostutil adapters gen from adapters/*/adapter.toml. DO NOT EDIT.

# workcell_supported_agent succeeds when $1 is a supported adapter id.
workcell_supported_agent() {
  case "$1" in
    claude | codex | copilot | gemini) ;;
    *)
      return 1
      ;;
  esac
}
